<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Presistance\Data\DataSeed\" />
    <Folder Include="Presistance\Repositories\Collaborators\" />
    <Folder Include="Presistance\Repositories\NotesInfo\" />
    <Folder Include="Presistance\Repositories\Tags\" />
    <Folder Include="Presistance\Repositories\Notes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.22.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\oteKeeperPro.Application\NoteKeeperPro.Application.csproj" />
  </ItemGroup>

</Project>
